#!/bin/bash

while getopts S:U:P: option
do
  case "${option}"
  in
    S) SERVER=${OPTARG};;
    U) USERNAME=${OPTARG};;
    P) PASSWORD=${OPTARG};;
    *) echo "Invalid option: -$OPTARG" >&2;;
  esac
done

podman run -it mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S $SERVER -U $USERNAME -P $PASSWORD
