#!/bin/bash

while getopts S:U:P: option
do
  case "${option}"
  in
    S) SERVER=${OPTARG};;
    U) USERNAME=${OPTARG};;
    P) PASSWORD=${OPTARG};;
    *) echo "Invalid option: -$OPTARG" >&2;;
  esac
done

if [ -z "$SERVER" ] || [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
  echo "Error: Missing required options -S, -U, or -P" >&2
  exit 1
fi

podman run -it mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S $SERVER -U $USERNAME -P $PASSWORD
